[package]
name = "neo-rimage"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "neo_rimage_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2.5.1"
tauri-plugin-process = "2.3.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
window-vibrancy = "0.7.1"
windows-version = "0.1.7"
crossbeam-channel = "0.5.16"
once_cell = "1.21.4"
serde_repr = "0.1.20"
sysinfo = "0.39.6"
walkdir = "2.5.0"
rimage = { path = "vendor/rimage", default-features = false, features = [
  "resize",
  "quantization",
  "mozjpeg",
  "metadata",
  "icc",
] }
zune-core = { version = "0.5.1", features = ["std"] }
zune-image = { version = "0.5.0", features = ["simd"] }
mozjpeg = { version = "0.10.13", default-features = false, features = ["with_simd"] }
